
services:
  consumer:
    build: .
    image: consumer_images
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - KAFKA_GROUP_ID=group2
      - KAFKA_AUTO_OFFSET_RESET=earliest
    command: ["python", "logistics_data_consumer.py"]
